site_name: CO-CONNECT Docs
theme:
  name: material
  palette:
    scheme: co-connect
  custom_dir: overrides      
  logo: images/favicon.png
  favicon: images/favicon.png
  features:
    - navigation.sections
    #- navigation.expand 
    #- toc.integrate
extra_css:
  - stylesheets/custom.css
    
nav:
  - Welcome: index.md
  #- Getting Started:
  #    - Introduction: GettingStarted/index-data-team.md
  #    - OHDSI-in-a-Box:
  #      - What is it?: GettingStarted/OHDSI-in-a-Box.md
  #      - Install: GettingStarted/install-OHDSI-in-a-Box.md
  #      - Exploring Datasets with Python: GettingStarted/explore-datasets-python.ipynb
  #    - WhiteRabbit: GettingStarted/white-rabbit.md
  - Azure Functions:
    - LocalFunctions: AzureFunctions/RunningLocally.md
    - ProcessQueue: AzureFunctions/processQueue.md
    - NLPQueue: AzureFunctions/nlpQueue.md

  - Mapping-Pipeline:
      - About:   MappingPipeline/about.md
      - Uploading a Report:   MappingPipeline/uploading-scan-report.md
      - Mapping Rules: MappingPipeline/mapping-rules.md
      - API: MappingPipeline/API.md      
      #- Downloading Mapping:   MappingPipeline/downloading-rules.md
      
  - CO-CONNECT Tools:
      - About: CoConnectTools/About.md
      - User Guide: 
          - Installing: CoConnectTools/Installing.md
          - ETL-Tool:
              - Guide: CoConnectTools/ETL-Tool.md   
              - Quick Example: CoConnectTools/QuickRun.md
          - FAQ: CoConnectTools/FAQ.md
      - Developer Guide:
          - Overview: CoConnectTools/CommonDataModel.md 
          - Tables:
              - Common: CoConnectTools/Common.md  
              - Person: CoConnectTools/Person.md
              - Condition Occurrence: CoConnectTools/ConditionOccurrence.md
              - Visit Occurrence: CoConnectTools/VisitOccurrence.md
              - Measurement: CoConnectTools/Measurement.md
              - Observation: CoConnectTools/Observation.md
              - Drug Exposure: CoConnectTools/DrugExposure.md
          - ETL Workbook Example: "CoConnectTools/notebooks/Introduction\ -\ Using\ the\ ETLTool.ipynb"
      - Additional Tools:
          - Command Line Interface: CoConnectTools/CommandLine.md
          - Generating Synthetic Data: CoConnectTools/SyntheticData.md

  - BCLink:
      - Test Link:
          - Via SSH: BCLink/TestLink/ssh.md

plugins:
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      write_markdown: false
      binder: false
      binder_service_name: "gh"
      binder_branch: "master"
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_if_no_docstring: true
            show_root_heading: true
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          setup_commands:
            - import sys
            - sys.path.append("docs/CoConnectTools/source_code/")
            - import coconnect


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - codehilite
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  
#extra_css:
#  - stylesheets/extra.css
  
#extra_javascript:
#  - javascripts/config.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - https://cdn.plot.ly/plotly-latest.min.js
