name: co-coconnect-tools
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6.8]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - run: ls .
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install co-connect-tools
        run:  pip3 install -e .
      - run: coconnect --help
  unit_test_py_config:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6.8]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: build
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - uses: actions/checkout@v2
      - run: ls .
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install co-connect-tools
        run:  pip3 install -e .
      - run: coconnect display json example/sample_config/lion_structural_mapping.json
      - run: coconnect map py make --name Lion --register  example/sample_config/lion_structural_mapping.json
      - run: coconnect map py list
      - run: coconnect map py run --conf Lion.py example/sample_input_data/*.csv
      - uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: output_data
          retention-days: 1
  unit_test_json_config_unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6.8]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: build
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - uses: actions/checkout@v2
      - run: ls .
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install co-connect-tools
        run:  pip3 install -e .
      - run: |
          COCONNECT_DATA_FOLDER=$(coconnect info data_folder)
          coconnect map run --rules $COCONNECT_DATA_FOLDER/test/rules/rules_14June2021.json --output-folder tests/ $COCONNECT_DATA_FOLDER/test/inputs/*.csv 
      - run: |
          for filename in tests/*.tsv; do
               fname=${filename##*/}
               coconnect display diff $filename coconnect/data/test/expected_outputs/$fname
          done

      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: tests
          retention-days: 1
  unit_test_json_config_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6.8]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: build
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - uses: actions/checkout@v2
      - run: ls .
      - name: Install setuptools
        run: pip3 install setuptools
      - name: Install co-connect-tools
        run:  pip3 install -e .
      - run: |
          coconnect map run --rules coconnect\data\test\rules\rules_14June2021.json --output-folder tests coconnect\data\test\inputs 
      - run: |
          $files = Get-ChildItem tests\*.tsv
          Foreach ($file in $files )
          {
              $newFile = $file.FullName
              $refFile = $('coconnect\data\test\expected_outputs\' + $file.Name)
              $command = $('coconnect display diff ' + $newFile + ' ' +  $refFile)
              Invoke-expression $command
          }
          
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: tests
          retention-days: 1
  pypi:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.8
      - run: pip3 install wheel
      - uses: actions/checkout@v2
      - run:  |
         echo "__version__ = '${GITHUB_REF#refs/*/}'" > coconnect/_version.py
         cat coconnect/_version.py
         python3 setup.py sdist bdist_wheel
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}
